### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by jratzenboeck** [michaelruocco/embedded-mysql-plugin#1]
When starting my unit test it cannot connect to the mysql database. Following is an extract of the stacktrace I receive:

Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
    at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694)
    at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1215)
    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255)
    at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2106)

Is there any known issue regarding this or did I make some mistake or missed something in the configuration?

**Comment by michaelruocco** [comment]
It is not something I have come across before so it is not a known issue, but that does not mean to say it doesn't mean there is any issue? Is the project that is having this issue available anywhere so that I can take a look at it?

I have only ever seen this type of issue before if the password has been set incorrectly, i.e. you have set up a password against when started the embedded database and not provided it when trying to connect or vice versa.

**Comment by jratzenboeck** [comment]
I use it in my Spring application and configured it like this:

## build.gradle

embeddedMysql {
    url = 'jdbc:mysql://localhost:3306/tmstest'
    username = 'root'
    password = 'root'
    version = 'v5_7_latest'
}

## application.properties

spring.datasource.url=jdbc:mysql://localhost:3306/tmstest?autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.jdbc.Driver

Just as reminder: The README file is not up-to-date here since it describes an outdated configuration regarding the first parameter of the embeddedMysql {...} part.

**Comment by michaelruocco** [comment]
I have had a play with the underlying library that the gradle plugin uses which can be found here: https://github.com/wix/wix-embedded-mysql. It seems that the library will only work if the password is blank for a root user, if you use any other username apart from root using a password seems to work fine.

So can you try either removing the password and leaving it to be blank, or changing the user to be something else e.g. testuser. Hopefully that should get around your issue, let me know if it does.

We may need to contact the authors of the actual embedded mysql library or take a look at that underlying code to see if we can find a way to specify a password for root, but I suspect this might be particularly difficult to do, which might be why it doesn't work currently.

Apologies for the outdated README example, I will get on and update that now, thanks for pointing it out!

**Comment by michaelruocco** [comment]
I have created another repo here https://github.com/michaelruocco/embedded-mysql-password-issue which demonstrates the issue pretty clearly. I will contact the author of the original library and see what their thoughts are on this. In the mean time hopefully using a blank password or changing the username has solved your issue. As I said previously, please let me know if that is not the case.

**Comment by michaelruocco** [comment]
@ratzi199 

Did changing the username or using a blank password work okay for you? I created this issue against the main library describing the issue you found: https://github.com/wix/wix-embedded-mysql/issues/58 we have decided that the solution will be to not allow the use of the root user, so to keep your change compatible you should probably just modify the username you are using.

Are you happy for me to close this issue?

**Comment by jratzenboeck** [comment]
Hi again! Unfortunately changing the username to something else or using the root user with no password did not help for me. I have already tried several combinations but all of them failed :( Maybe there is another issue with the database created by the plugin. I do not have to create the database or anything else beforehand. Just be connected to MySql on port 3306 before I run my tests suffices, right?

**Comment by michaelruocco** [comment]
Hmmm that is strange, I haven't had any luck recreating the error. But yes as long as the database has started and is running before you try to connect to it from your tests you should be okay. I would be happy to take a look if you have some code you can share that recreates the issue.

**Comment by jratzenboeck** [comment]
Sorry for my late answer now. We did not have time to investigate further regarding this concrete problem. Therefore we solved the problem by using an external MySql database (create-drop mode) since we use it for our unit tests. From my side the issue can be closed. However, thanks for your support.
