### ISSUE TITLE
gradle kotlin dsl: cannot configure embeddedMysql section

### ISSUE THREAD

**Issue by pvanek** [michaelruocco/embedded-mysql-plugin#15]
I have these sections in my `build.gradle.kts`

plugins:
```
id("com.github.michaelruocco.embedded-mysql-plugin") version "2.1.11"
```

```
embeddedMysql {
    url = "jdbc:mysql://localhost:3306/test"
    username = "test"
    password = "test"
    version = "v5_7_27"
}
```

build (and IDE) shows following errors:

```
* What went wrong:
Script compilation errors:

  Line 170:     url = "jdbc:mysql://localhost:3306/test"
                ^ Unresolved reference: url

  Line 173:     version = "v5_7_27"
                ^ Val cannot be reassigned

  Line 173:     version = "v5_7_27"
                          ^ Type mismatch: inferred type is String but Version! was expected

3 errors
```

The 3rd error: "version cannot be string" can be fixed with:
```
com.wix.mysql.distribution.Version.v5_7_27
```
constant

Is there something I can do with rest of it?

**Comment by pvanek** [comment]
workaround:

```
embeddedMysql {
    setUrl("jdbc:mysql://localhost:3306/test")
    username = "test"
    password = "test"
    setVersion(com.wix.mysql.distribution.Version.v5_7_27) // or setVersion("v5_7_27")
}
```

**Comment by michaelruocco** [comment]
Hi @pvanek, apologies for the delay, I have had a busy Christmas. Apologies, I am not overly familiar with Kotlin? Is there a fix or change that would help you with this, or is the work around you have posted above sufficient for now?

**Comment by pvanek** [comment]
no problem at all. The solution I posted above is fine. I'd just update the README file with a sub-section for Kotlin DSL. I can prepare a PR if you wish

**Comment by michaelruocco** [comment]
Ah okay that makes sense. Yeah if you wouldn’t mind that would be great? If not I’ll use what you’ve added here and try and add it when I get around to it.

**Comment by pvanek** [comment]
https://github.com/michaelruocco/embedded-mysql-plugin/pull/16
