### ISSUE TITLE
Download and Extract fails

### ISSUE THREAD

**Issue by fieldju** [michaelruocco/embedded-mysql-plugin#2]
When I attempt to run 

    startEmbeddedMysql

No matter which version I use, I get the following

build.gradle

    classpath 'com.github.michaelruocco:embedded-mysql-plugin:2.1.3'
    ...
    apply plugin: 'embedded-mysql'
    ...

    embeddedMysql {
        url = 'jdbc:mysql://localhost:3306/cms'
        username = 'cms'
        password = 'P@ssw0rd'
        version = 'v5_7_13'
    }

stdout

    :startEmbeddedMysql
    Download Version 5.7.10:OS_X:B64 START
    Download Version 5.7.10:OS_X:B64 DownloadSize: 0
    Download Version 5.7.10:OS_X:B64 downloaded with 0kb/s
    Download Version 5.7.10:OS_X:B64 DONE
    Extract /Users/jfiel2/.embedmysql/MySQL-5.7/mysql-5.7.10-osx10.9-x86_64.tar.gz START

    --------------------------
    If you get this exception more than once, you should check if the file is corrupt.
    If you remove the file (/Users/jfiel2/.embedmysql/MySQL-5.7/mysql-5.7.10-osx10.9-x86_64.tar.gz), it will be downloaded again.
    --------------------------
    no message
    java.io.IOException: File /Users/jfiel2/.embedmysql/MySQL-5.7/mysql-5.7.10-osx10.9-x86_64.tar.gz

It appears from the stdout and manually looking in the dir that its downloading empty files

**Comment by michaelruocco** [comment]
Hi Justin,

I have taken a quick look at this. The library that this plugin builds on top of is this one: https://github.com/wix/wix-embedded-mysql. This library contains a DownloadConfigBuilder which you can see here: https://github.com/wix/wix-embedded-mysql/blob/master/src/main/java/com/wix/mysql/config/DownloadConfigBuilder.java. Line 14 of this contains the config for the download path "https://dev.mysql.com/get/Downloads/".

When I try to navigate to that page, I get a page not found response on the MySQL website. The downloads page it actually at the url "https://www.mysql.com/downloads/". My guess is this url on the website has moved. I will raise this with the authors of the underlying library to see if it can be fixed.

**Comment by michaelruocco** [comment]
@fieldju

Just to update, I raised this issue against the underlying library project:  https://github.com/wix/wix-embedded-mysql/issues/82 and as you can see I had a very quick response. Once a new version of https://github.com/wix/wix-embedded-mysql has been released, I will update this library with the latest version and following that it should be working as expected again.

**Comment by michaelruocco** [comment]
@fieldju 

I have just pushed a new version 2.1.4 and released a new version, it should be available on maven central soon. Once it is, please try again using the updated version and let me know if you still encounter any issues. If not then I will close this issue, but I will wait for you to confirm.

**Comment by fieldju** [comment]
Nice, I will check it out now and report back. Thanks for the quick response.

**Comment by fieldju** [comment]
Amazing, works perfectly!

Now I have no external dependencies for running my project locally.

Cheers,

Justin

**Comment by michaelruocco** [comment]
Excellent, glad it is working as expected. I will go ahead and close this issue, thanks for flagging it up.
