### ISSUE TITLE
Publish to Gradle plugin repository?

### ISSUE THREAD

**Issue by clayreimann** [michaelruocco/embedded-mysql-plugin#4]
It would be awesome if we could use the new gradle plugin syntax for this plugin!

Instructions for submitting the plugin [are here](https://plugins.gradle.org/docs/submit)

**Comment by michaelruocco** [comment]
@clayreimann thanks for the suggestion.

You should be able to find it here: https://plugins.gradle.org/plugin/com.github.michaelruocco.embedded-mysql-plugin now. Can you try it out please? If it works okay I will see about adding some documentation to the readme.

**Comment by clayreimann** [comment]
@michaelruocco Thanks! I haven't gotten a chance to test yet, but I hope to soon

**Comment by michaelruocco** [comment]
I am confident this is working as expected from the gradle plugin repository so I am going to close this issue. Feel free to raise a new one if you run into any issues when you get a chance to test it.
