### ISSUE TITLE
Expose a way to configure artifact store in the plugin extension  

### ISSUE THREAD

**Issue by ezraroi** [michaelruocco/embedded-mysql-plugin#6]
Hi,
the wix guys added a way to config some of the directories they use.
Can this be configure via the plugin extension?  

https://github.com/wix/wix-embedded-mysql/pull/96

**Comment by michaelruocco** [comment]
Hi,

I should think it is probably possible. I will need to have a read and catch up with the changes made to the library. I am pretty stacked out with work at the moment, so it might be a while before I can take a look. Feel free to have a look and raise a pull request if you have time.

Thanks,

**Comment by ezraroi** [comment]
sure , will do so

**Comment by michaelruocco** [comment]
Hi @ezraroi have you had any joy with this yet? Unfortunately I have not been able to find any time to look at this recently. I am hoping I might be able to find some time in a few weeks or so.

**Comment by ezraroi** [comment]
Hi, yes this will help us. i am trying to find time also and to do PR.

Thanks

**Comment by michaelruocco** [comment]
Hi @ezraroi,

I have finally gotten around to adding this functionality into the plugin under version 2.1.6, apologies for the long delay but I have been very busy with my work projects recently. Please feel free to give it a true and let me know how you get on. If you get time to give it a try and let me know you are happy it is fixed then I will close the issue.

Thanks.

**Comment by jakemonO** [comment]
I am using the custom cache directory feature, but I'm confused about where the actual schema tables get created - I can't find them in that custom directory where MySQL was expanded. In a nutshell, I am trying to use the feaure to instantiate MySQL on a RAMDisk for faster unit testing on a continuos build server, but its obviously not running on the RAMDisk as I thought...

UPDATE: I see that the datadir is ALWAYS in the PROJECT_ROOT/target directory and cannot be overridden witrh the datadir MySQL param. Any way/plans to change that?

**Comment by michaelruocco** [comment]
Hi @jakemonO @ezraroi is this still causing you problems or can this issue be closed?

**Comment by michaelruocco** [comment]
I am going to close this one as I don't see a way to set the data dir param in the underlying wix library, if you can raise an issue their and see if they can implement the functionality then it should be pretty easy for me to expose through the plugin.
