### ISSUE TITLE
wishlist: specify disk location for mysql (ramdisk)

### ISSUE THREAD

**Issue by jakemonO** [michaelruocco/embedded-mysql-plugin#8]
any way to specify the disk location for the instance? for unit tests, we like to run mysql on a ramdisk for speed and it would be helpful to be able to execute the plugin's mysql instance similarly. currently, the plugin's mysql takes about 2x the time of our legacy mysql running on a ramdisk

**Comment by michaelruocco** [comment]
Hi @jakemonO,

This was added to the underlying project a while back with [this pull request](https://github.com/wix/wix-embedded-mysql/pull/96) was also requested by [this](https://github.com/michaelruocco/embedded-mysql-plugin/issues/6) issue as well. 

I have finally gotten around to adding this functionality into the plugin under version 2.1.6, apologies for the long delay but I have been very busy with my work projects recently. Please feel free to give it a true and let me know how you get on.

Thanks.
