### ISSUE TITLE
specify runtime location

### ISSUE THREAD

**Issue by jakemonO** [michaelruocco/embedded-mysql-plugin#9]
not sure if this is a gradle limitation or the plugin's but it would be nice to be able to specify the file location to execute the plugin and/or the data directory from. My use case is that I would like the datadir to be on a RAM disk for faster throughput. In my case, its the difference between a 25 minute build and a 1 and a half hour one...

**Comment by michaelruocco** [comment]
Hi @jakemonO, I have attempted to add this functionality now and I believe it should be working, I added a comment to the previous issue that you raised before I closed it, https://github.com/michaelruocco/embedded-mysql-plugin/issues/8. Feel free to give the new version a try and let me know how you get on with it.

Thanks.

**Comment by jakemonO** [comment]
issue #8 is not quite the same. The MySQL instance is always created in the rootDir/target/mysql-major.minor-guid folder. The instance itself should be run from a custom location (such as a RAM disk) or at least I wish I could specify a data dir for the MySQL instance that would be in a RAM disk.

**Comment by michaelruocco** [comment]
Hi @jakemonO is this still causing you a problem or are you happy for it to be closed?

**Comment by jakemonO** [comment]
I need a day or two to test. Is that OK?

**Comment by jakemonO** [comment]
I've been working around the issue for quite some time. I can try to test it specifically in the coming week I'd you don't mind waiting, otherwise, I'm ok with the issue being closed.

**Comment by michaelruocco** [comment]
I am happy to wait, if you have a proposal for a fix / change I don't mind trying to include it in the plugin. I think I am just not clear how it could be done unless the underlying wix library supports it already?

**Comment by michaelruocco** [comment]
Have closed, this issue for now, happy to reopen if required.
